<?php

use \Drupal\views\ViewExecutable;
use Drupal\views\ResultRow;

/**
 * Implements hook_views_pre_render()
 * @param \Drupal\views\ViewExecutable $view
 */
function portal_preprocess_views_view_unformatted(&$variables) {
  $view = $variables['view'];
  
  if ($view->id() == 'products_categories_link') {
    if ($term = \Drupal::routeMatch()->getParameter('taxonomy_term')) {
      $tid = $term->id();
      $variables['allclass'] = '';
    }
    else {
      $tid = 0;
      $variables['allclass'] = 'row-active';
    }
    $rows = &$variables['rows'];
    foreach ($rows as $row) {
      if($row['content']['#row']->_entity->id() == $tid) {
        $row['attributes']->addClass('row-active');
      }
    }
  }
}